#!/usr/bin/env bash

# Install command-line tools using Homebrew.

# Install Homebrew
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# Make sure we’re using the latest Homebrew.
brew update

# Upgrade any already-installed formulae.
brew upgrade --all

brew tap Homebrew/bundle

brew bundle --global

# Set up GNU core utilities (those that come with OS X are outdated).
echo 'Be sure to add `$(brew --prefix coreutils)/libexec/gnubin` to `$PATH`.'

if ! grep -Fq '/usr/local/bin/bash' /etc/shells; then
  echo '/usr/local/bin/bash' | sudo tee -a /etc/shells;
  chsh -s /usr/local/bin/bash;
fi;

# Remove outdated versions from the cellar.
brew cleanup

# Set up Solarized Light syntax highlighting for bat
BAT_THEMES_DIR="$(bat cache --config-dir)/themes"
if [ ! -d "$BAT_THEMES_DIR" ]; then
  mkdir -p "$BAT_THEMES_DIR"
  git -C "$BAT_THEMES_DIR" clone --quiet https://github.com/braver/Solarized
  git -C "$BAT_THEMES_DIR" checkout 87e01090cf
fi
