#!/bin/bash

source ./utils

run_npm() {
    # Check for npm
    if type_exists 'npm'; then
        e_header "Installing Node.js packages..."

        # List of npm packages
        local packages="
                        bower
                        alfred-change-case
                        coffee-script
                        emojipacks
                        eslint
                        eslint-config-semistandard
                        eslint-config-standard
                        eslint-plugin-import
                        eslint-plugin-node
                        eslint-plugin-promise
                        eslint-plugin-react
                        eslint-plugin-standard
                        generator-hubot
                        grunt-cli
                        jshint
                        lighthouse
                        prettier
                        semistandard
                        standard
                        textlint
                        travis-ci
                        travis-watch
                        yo
        "

        # Install packages globally and quietly
        npm install $packages --global --quiet

        [[ $? ]] && e_success "Done"
    else
        printf "\n"
        e_error "Error: npm not found."
        printf "Aborting...\n"
        exit
    fi
}
# Install Node packages
run_npm
