#!/usr/bin/env bash

source ./utils

run_npm() {
    # Check for npm
    if type_exists 'npm'; then
        e_header "Installing Node.js packages..."

        # List of npm packages
        local packages="
                        alex
                        alfred-polyglot
                        alfred-show-network-info
                        csslint
                        emojipacks
                        eslint
                        eslint-plugin-import
                        eslint-plugin-node
                        eslint-plugin-promise
                        eslint-plugin-react
                        eslint-plugin-standard
                        eslint-config-standard
                        eslint-config-semistandard
                        generator-hubot
                        grunt-cli
                        htmlhint
                        jshint
                        lighthouse
                        prettier
                        semantic-release-cli
                        textlint
                        travis-ci
                        travis-watch
                        yo
                        @commitlint/cli
                        @commitlint/config-conventional
        "

        # Install packages globally and quietly
        npm install $packages --global --quiet

        [[ $? ]] && e_success "Done"
    else
        printf "\n"
        e_error "Error: npm not found."
        printf "Aborting...\n"
        exit
    fi
}
# Install Node packages
run_npm
