#!/usr/bin/env bash

declare -a packages=(
	"pip"
	"setuptools"
	"wheel"
	"black"
	"flake8"
	"git-sweep3k"
	"pycodestyle"
	"pyflakes"
	"tabfix"
)

for pkg in "${packages[@]}"; do
	pip3 install --upgrade "$pkg"
done
