#!/usr/bin/env bash

declare -a packages=(
	"pip"
	"setuptools"
	"wheel"
	"flake8"
	"git-sweep"
	"pycodestyle"
	"tabfix"
	"yamllint"
)

for pkg in "${packages[@]}"
do
	pip3 install --upgrade "$pkg"
done
